/**
 * 🚀 PressButton 项目环境自动配置脚本
 *
 * 功能：
 * - 检查并创建必要的环境文件
 * - 为新同事提供一键环境搭建
 * - 支持本地开发和Docker环境
 *
 * 使用方法：
 * npm run setup
 */

const fs = require('fs');
const path = require('path');

// 颜色输出工具
const colors = {
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  blue: '\x1b[34m',
  reset: '\x1b[0m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

/**
 * 创建前端环境配置
 */
function setupWebEnvironment() {
  const webEnvPath = path.join(__dirname, '../pressbutton-web/.env.local');

  if (!fs.existsSync(webEnvPath)) {
    const webEnvContent = `# PressButton Web - Local Development Environment
# Auto-generated by setup script on ${new Date().toISOString()}

# API Configuration - 注意：必须包含 /api 后缀
NEXT_PUBLIC_API_URL=http://localhost:3001/api

# Development Environment
NODE_ENV=development

# 🔧 开发提示：
# - 本地开发使用 localhost:3001
# - Docker 环境会自动使用 docker-backend:3001
# - 生产环境使用 productionTodo
`;

    fs.writeFileSync(webEnvPath, webEnvContent);
    log('✅ Created pressbutton-web/.env.local', 'green');
    return true;
  } else {
    log('ℹ️  pressbutton-web/.env.local already exists', 'yellow');
    return false;
  }
}

/**
 * 创建后端环境配置
 */
function setupApiEnvironment() {
  const apiEnvPath = path.join(__dirname, '../pressbutton-api/.env');

  if (!fs.existsSync(apiEnvPath)) {
    const apiEnvContent = `# PressButton API - Local Development Environment
# Auto-generated by setup script on ${new Date().toISOString()}

# PostgreSQL Database Configuration
DATABASE_URL=postgresql://postgres:admin123@localhost:5432/pressbutton_dev

# JWT Authentication Configuration
JWT_SECRET=dev-secret-key-${Date.now()}-change-in-production
JWT_EXPIRES_IN=7d

# Server Configuration
PORT=3001
NODE_ENV=development

# CORS Configuration - 允许前端访问
CORS_ORIGIN=http://localhost:3000

# Rate Limiting Configuration
THROTTLE_TTL=60000
THROTTLE_LIMIT=100

# 🔧 开发提示：
# - 请确保 PostgreSQL 已启动并创建了 pressbutton_dev 数据库
# - JWT_SECRET 在生产环境中请使用强随机密钥
# - 数据库密码请根据你的本地配置修改
`;

    fs.writeFileSync(apiEnvPath, apiEnvContent);
    log('✅ Created pressbutton-api/.env', 'green');
    return true;
  } else {
    log('ℹ️  pressbutton-api/.env already exists', 'yellow');
    return false;
  }
}

/**
 * 创建 Docker 环境配置
 */
function setupDockerEnvironment() {
  const dockerEnvPath = path.join(__dirname, '../.env.docker');

  const dockerEnvContent = `# PressButton Docker Environment Configuration
# Auto-generated by setup script on ${new Date().toISOString()}

# ===========================================
# Docker Services Configuration
# ===========================================

# Frontend Docker Environment
NEXT_PUBLIC_API_URL=http://docker-backend:3001/api

# Backend Docker Environment
DATABASE_URL=postgresql://postgres:admin123@postgres:5432/pressbutton_dev
JWT_SECRET=docker-secret-key-change-in-production
PORT=3001
NODE_ENV=development
CORS_ORIGIN=http://localhost:3000

# Database Configuration
POSTGRES_DB=pressbutton_dev
POSTGRES_USER=postgres
POSTGRES_PASSWORD=admin123

# 🐳 Docker 提示：
# - 容器内服务通过服务名通信 (docker-backend, postgres)
# - 外部访问仍使用 localhost 端口映射
`;

  fs.writeFileSync(dockerEnvPath, dockerEnvContent);
  log('✅ Created .env.docker for Docker environment', 'green');
}

/**
 * 检查必要的目录和文件
 */
function checkProjectStructure() {
  const requiredDirs = [
    'pressbutton-web',
    'pressbutton-api'
  ];

  const missingDirs = requiredDirs.filter(dir =>
    !fs.existsSync(path.join(__dirname, '..', dir))
  );

  if (missingDirs.length > 0) {
    log('❌ Missing required directories:', 'red');
    missingDirs.forEach(dir => log(`   - ${dir}`, 'red'));
    return false;
  }

  return true;
}

/**
 * 主要设置函数
 */
function setupEnvironment() {
  log('\n🚀 Starting PressButton Environment Setup...', 'blue');
  log('=' .repeat(50), 'blue');

  // 检查项目结构
  if (!checkProjectStructure()) {
    log('\n❌ Setup failed: Project structure incomplete', 'red');
    process.exit(1);
  }

  let changesCount = 0;

  // 设置前端环境
  if (setupWebEnvironment()) changesCount++;

  // 设置后端环境
  if (setupApiEnvironment()) changesCount++;

  // 设置Docker环境
  setupDockerEnvironment();
  changesCount++;

  // 完成提示
  log('\n' + '=' .repeat(50), 'blue');
  log('🎉 Environment Setup Complete!', 'green');
  log(`📝 ${changesCount} configuration files created/updated`, 'green');

  log('\n📋 Next Steps:', 'blue');
  log('1. 检查并修改数据库连接配置（如果需要）', 'yellow');
  log('2. 确保 PostgreSQL 服务已启动', 'yellow');
  log('3. 运行 npm run dev 启动开发环境', 'yellow');
  log('4. 或运行 npm run docker:dev 启动 Docker 环境', 'yellow');

  log('\n🔗 Useful Commands:', 'blue');
  log('- npm run dev          # 启动本地开发', 'yellow');
  log('- npm run docker:dev   # 启动 Docker 开发', 'yellow');
  log('- npm run setup        # 重新运行此脚本', 'yellow');
}

// 运行设置
try {
  setupEnvironment();
} catch (error) {
  log(`\n❌ Setup failed: ${error.message}`, 'red');
  process.exit(1);
}
